In [1]:
import pandas as pd
import os
from typing import Optional

In [10]:
# def combine_csv_files(input_directory, output_file, id_column: Optional):
#     """
#     Reads all CSV files in a directory, combines them into one DataFrame,
#     removes duplicate rows based on a specific ID column, and saves the result to a single CSV.

#     Parameters:
#         input_directory (str): Path to the directory containing the CSV files.
#         output_file (str): Path to save the final combined CSV.
#         id_column (str): The column name to identify duplicates.

#     Returns:
#         None
#     """
#     # List all CSV files in the directory
#     csv_files = [file for file in os.listdir(input_directory) if file.endswith('.csv')]
#     print(f"Found {len(csv_files)} CSV files in '{input_directory}'.")

#     combined_df = pd.DataFrame()  # Initialize an empty DataFrame

#     # Read and append each CSV file
#     for csv_file in csv_files:
#         file_path = os.path.join(input_directory, csv_file)
#         print(f"Reading {file_path}...")
#         try:
#             df = pd.read_csv(file_path)
#             combined_df = pd.concat([combined_df, df], ignore_index=True)
#         except Exception as e:
#             print(f"Error reading {csv_file}: {e}")

#     # Remove duplicate rows based on the specified ID column
#     before_dedup = combined_df.shape[0]
#     # combined_df = combined_df.drop_duplicates(subset=[id_column])
#     combined_df = combined_df.drop_duplicates()
#     after_dedup = combined_df.shape[0]
#     #print(f"Removed {before_dedup - after_dedup} duplicate rows based on '{id_column}'.")
#     print(f"Removed {before_dedup - after_dedup} duplicate rows.")

#     # Save the combined DataFrame to a new CSV
#     combined_df.to_csv(output_file, index=False)
#     print(f"Combined data saved to '{output_file}'.")

In [11]:
# input_directory = "data/location_data"
# output_file = "data/combined_locations.csv"
# #id_column = "Place ID"

# combine_csv_files(input_directory, output_file, id_column)

In [12]:
# # Example usage
# input_directory = "data/review_data"  # Directory containing the 4 CSV files
# output_file = "data/combined_reviews.csv"

# combine_csv_files(input_directory, output_file, id_column)

In [15]:
# def consolidate_text_files(input_directory, output_file):
#     """
#     Consolidates all text files in a directory into a single text file, removing duplicate lines.

#     Parameters:
#         input_directory (str): Path to the directory containing text files.
#         output_file (str): Path to save the consolidated text file.

#     Returns:
#         None
#     """
#     try:
#         unique_lines = set()  # Set to store unique lines

#         # Iterate through all files in the directory
#         for filename in os.listdir(input_directory):
#             if filename.endswith(".txt"):  # Only process .txt files
#                 file_path = os.path.join(input_directory, filename)
#                 print(f"Processing: {file_path}")

#                 # Read the contents of the text file
#                 with open(file_path, "r") as infile:
#                     for line in infile:
#                         unique_lines.add(line.strip())  # Add lines to the set (removes duplicates)

#         # Write unique lines to the output file
#         with open(output_file, "w") as outfile:
#             for line in sorted(unique_lines):  # Sort for consistent order (optional)
#                 outfile.write(line + "\n")

#         print(f"All text files have been consolidated into '{output_file}' with duplicates removed.")
#     except Exception as e:
#         print(f"An error occurred: {e}")

In [16]:
# # Example usage
# input_directory = "data/location_data/maps_urls"  # Directory containing text files
# output_file = "data/consolidated_urls.txt"  # Output consolidated text file
# consolidate_text_files(input_directory, output_file)

## Version 2

In [17]:
ratings_df = pd.read_csv("data/naturals_chennai_locations_metadata.csv")
sentiments_df = pd.read_csv("data/naturals_sentiments.csv")

In [18]:
ratings_df.head()

,Unnamed: 0,Location ID,City Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL,full_location
0,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...,Alwarpet Naturals Salon & Spa CP Ramaswamy roa...
1,1,LOC_2,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,656,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...,Alwarpet Naturals Lounge TTK
2,2,LOC_3,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...,Alwarpet Naturals Salon
3,6,LOC_1,"Adambakkam, Brindavan Nagar",Naturals Salon,"N37 First Flr, 2nd Street Shawalace Col, Brind...",12.986571,80.205181,4.9,353,ChIJD93nXvxdUjoRinIO5qSoRrc,https://www.google.com/maps/place/?q=place_id:...,"Adambakkam, Brindavan Nagar Naturals Salon"
4,7,LOC_2,"Adambakkam, Brindavan Nagar",Naturals Salon,"No.16A/17, Secretariat Colony Main Road, City ...",12.997302,80.207245,4.6,1363,ChIJP8-7AF1nUjoR3_YHwKTtq28,https://www.google.com/maps/place/?q=place_id:...,"Adambakkam, Brindavan Nagar Naturals Salon"

In [26]:
ratings_df["full_location"] = ratings_df["City Area"] + ratings_df["Name"]

In [27]:
ratings_df.head()

,Unnamed: 0,Location ID,City Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,Google Maps URL,full_location
0,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,https://www.google.com/maps/place/?q=place_id:...,AlwarpetNaturals Salon & Spa CP Ramaswamy road...
1,1,LOC_2,Alwarpet,Naturals Lounge TTK,"No.220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043691,80.259478,4.6,656,ChIJfwi_pjZmUjoRtNJzL20D2-A,https://www.google.com/maps/place/?q=place_id:...,AlwarpetNaturals Lounge TTK
2,2,LOC_3,Alwarpet,Naturals Salon,"No 220, Mowbrays Flats, TT Krishnamachari Rd, ...",13.043618,80.259485,5.0,1,ChIJ1cEdFYpnUjoRBTQevSN3-mU,https://www.google.com/maps/place/?q=place_id:...,AlwarpetNaturals Salon
3,6,LOC_1,"Adambakkam, Brindavan Nagar",Naturals Salon,"N37 First Flr, 2nd Street Shawalace Col, Brind...",12.986571,80.205181,4.9,353,ChIJD93nXvxdUjoRinIO5qSoRrc,https://www.google.com/maps/place/?q=place_id:...,"Adambakkam, Brindavan NagarNaturals Salon"
4,7,LOC_2,"Adambakkam, Brindavan Nagar",Naturals Salon,"No.16A/17, Secretariat Colony Main Road, City ...",12.997302,80.207245,4.6,1363,ChIJP8-7AF1nUjoR3_YHwKTtq28,https://www.google.com/maps/place/?q=place_id:...,"Adambakkam, Brindavan NagarNaturals Salon"

In [28]:
sentiments_df.head()

,Unnamed: 0,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id,sentiment
0,1,ChZDSUhNMG9nS0VJQ0FnSUR2NVptekJnEAE,"Rosika did an excellent facial, great neck mas...",22 hours ago,2024-12-23 15:22:09.507031,2024-12-23 15:22:09.507073,5.0,Sujatha Madangopal,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
1,2,ChdDSUhNMG9nS0VJQ0FnSUR2NGJMZndBRRAB,had a great hair washing and blow dry experien...,2 days ago,2024-12-21 15:22:09.507740,2024-12-23 15:22:09.507785,5.0,080 harshitha sridhar,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
2,3,ChdDSUhNMG9nS0VJQ0FnSUR2dHN1WG9nRRAB,Excellent face massage by Goweri Thankyou you...,2 days ago,2024-12-21 15:22:09.507917,2024-12-23 15:22:09.507958,5.0,Varun Bala Vk,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
3,4,ChZDSUhNMG9nS0VJQ0FnSUNLdUtTR1NREAE,Aakash raj - Did very good haircut and shave s...,3 days ago,2024-12-20 15:22:09.508090,2024-12-23 15:22:09.508131,5.0,Rajesh Gopalsamy,23,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
4,5,ChZDSUhNMG9nS0VJQ0FnSUR2M01DbWR3EAE,Excellent hair spa service by Rosika,4 days ago,2024-12-19 15:22:09.508263,2024-12-23 15:22:09.508304,5.0,Kaviya,19,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive

In [29]:
len(ratings_df)

148

In [30]:
len(sentiments_df)

46522

In [31]:
combined_df = pd.merge(ratings_df, sentiments_df, left_on="Place ID", right_on="place_id", how="right")

In [32]:
len(combined_df)

46522

In [33]:
combined_df.head()

,Unnamed: 0_x,Location ID,City Area,Name,Address,Latitude,Longitude,Rating,Total Reviews,Place ID,...,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,place_id,sentiment
0,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,...,ChZDSUhNMG9nS0VJQ0FnSUR2NVptekJnEAE,"Rosika did an excellent facial, great neck mas...",22 hours ago,2024-12-23 15:22:09.507031,2024-12-23 15:22:09.507073,5.0,Sujatha Madangopal,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
1,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,...,ChdDSUhNMG9nS0VJQ0FnSUR2NGJMZndBRRAB,had a great hair washing and blow dry experien...,2 days ago,2024-12-21 15:22:09.507740,2024-12-23 15:22:09.507785,5.0,080 harshitha sridhar,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
2,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,...,ChdDSUhNMG9nS0VJQ0FnSUR2dHN1WG9nRRAB,Excellent face massage by Goweri Thankyou you...,2 days ago,2024-12-21 15:22:09.507917,2024-12-23 15:22:09.507958,5.0,Varun Bala Vk,0,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
3,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,...,ChZDSUhNMG9nS0VJQ0FnSUNLdUtTR1NREAE,Aakash raj - Did very good haircut and shave s...,3 days ago,2024-12-20 15:22:09.508090,2024-12-23 15:22:09.508131,5.0,Rajesh Gopalsamy,23,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive
4,0,LOC_1,Alwarpet,"Naturals Salon & Spa CP Ramaswamy road , Alwar...","No.37, 1st Floor, CP Ramaswamy Iyer Rd, opp. t...",13.032512,80.256971,4.6,1078,ChIJB0quoslnUjoRf_vm8BiGHsM,...,ChZDSUhNMG9nS0VJQ0FnSUR2M01DbWR3EAE,Excellent hair spa service by Rosika,4 days ago,2024-12-19 15:22:09.508263,2024-12-23 15:22:09.508304,5.0,Kaviya,19,ChIJB0quoslnUjoRf_vm8BiGHsM,Positive